### ISSUE TITLE
timbre/logp not found

### ISSUE THREAD

**Issue by noncom** [ptaoussanis/tower#67]
Using tower `3.0.2` I get the error that `timbre/logp` is not found because some other library is using timbre `4.1.1` and this version of tower is using timbre `3.4.0`. Even when I specify timbre `3.4.0`, it says `No such var: encore/cond!, compiling:(taoensso/tower.clj:371:4)` which I did not investigate further, but that effectively prevents me from using tower.

**Comment by ptaoussanis** [comment]
Hi Alex, sounds like you have a dependency conflict - you can use `lein deps :tree` to find the conflicting deps. Please see [here](https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md) for details.

Does that help?

**Comment by kevindragon** [comment]
I am also come with this problem.

 [com.taoensso/timbre "4.1.1"]
   [com.taoensso/encore "2.4.2"]
   [io.aviso/pretty "0.1.18"]
 [com.taoensso/tower "3.0.2"]

**Comment by ptaoussanis** [comment]
Ah, my apologies - `logp` was removed from Timbre v4 (it was deprecated in v3) and you must be using some code that's still relying on it.

I've just pushed `[com.taoensso/timbre "4.1.2"]` which adds `logp` back. Just make sure you're using that and a recent version of Encore (latest is 2.18.0), and you should be good to go :-)

**Comment by noncom** [comment]
Wow, guys, you were so fast! Cool :)
