### ISSUE TITLE
Wrong Swedish currency output

### ISSUE THREAD

**Issue by hermelinstil** [ptaoussanis/tower#69]
```clojure
(fmt :sv-SE 200 :currency)
=> "200,00 kr"
```
All is correct

```clojure
(fmt :sv-SE 2000 :currency)
=> "2á000,00 kr"
;; Should be => "2000,00 kr"
```
This happens for every thousand:

```clojure
(fmt :sv-SE 2000000 :currency)
=> "2á000á000,00 kr"
;; Should be => "2000000,00 kr"
```

**Comment by ptaoussanis** [comment]
Hey there,

Could this possibly be a JVM resource / font issue?

`((fmt :sv-SE 2000000 :currency)` translates into
`(.format (NumberFormat/getCurrencyInstance (locale :sv-SE)) 2000)`
which produces "2 000,00 kr" on my device

Note that the space between the 2 and 0 is actually the non-breaking-space unicode character (\x{A0}). In my emacs, it looks like a "_". But it's rendering correctly in my browser (Chrome).

**Comment by hermelinstil** [comment]
Ah, yes!

You are correct, sorry for the late reply.
