### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by Eeveline** [ptaoussanis/tower#71]
With 3.1.0-beta4 I get this exception:
```
#error {
 :cause Insufficient com.taoensso/encore version (< 1.21). You may have a Leiningen dependency conflict (see http://goo.gl/qBbLvC for solution).
 :data {:min-version 1.21}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message failed compiling ...
```
I don't have encore as a direct dependency in my project. The dependency I import is: 
```[com.taoensso/tower "3.1.0-beta4" :exclusions [com.taoensso/encore]].```

I believe it is the same problem as this: https://github.com/ptaoussanis/timbre/issues/143

**Comment by ptaoussanis** [comment]
Hi Eveline,

Were the ideas at http://goo.gl/qBbLvC unsuccessful?

> I don't have encore as a direct dependency in my project. The dependency I import is: 
[com.taoensso/tower "3.1.0-beta4" :exclusions [com.taoensso/encore]].

Is there a reason you're excluding Encore here? Encore's a required dependency for Tower. If you're excluding it here, you'll need to include an explicit dependency yourself.

If the instructions at http://goo.gl/qBbLvC aren't working, please get me your `lein deps :tree` output?

Cheers :-)

**Comment by Eeveline** [comment]
Turns out another dependency imports an old version of encore. One of my colleagues added the tower dependency, so I will have to ask him why he excluded encore. Thanks!
